#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

bash $HOME/.fehbg

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#2E3440"
bspc config active_border_color "#B48EAD"
bspc config presel_feedback_color "#A3BE8C"

$HOME/.config/polybar/launch.sh

